version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=baklanov
      - POSTGRES_PASSWORD=levelLock
      - POSTGRES_DB=tjv
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    external: true